spring:
  datasource:
    username: root
    password: 11255917
    url: jdbc:mysql://localhost:3306/xtu_news? serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xtu.news.pojo
  global-config:
    db-config:
      id-type: auto


#jwt加密
admin:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: authorization
server:
  port: 80
file:
  upload:
    url: D:/programming/Demo/SpringBootStudy/articcle/src/main/java/com/hp/test
  download:
    url: D:\programming\Demo\SpringBootStudy\articcle\src\main\java\com\hp\test

jasypt:
  encryptor:
    password: xtuNews
